<MyGridLayout>

    oldsalary:oldsalary

    GridLayout:
        cols:1
        size: root.width, root.height
        padding: 50
        spacing: 20
        GridLayout:
            cols:2

            Label:
                text: "Username"
                font_size: 32
                size_hint: (1, 0.2)


            TextInput:
                id: oldsalary
                multiline:False
                size_hint: (1, 0.2)

            Label:
                id: name_label
                text: "Password"
                font_size: 32
                size_hint: (1, 0.2)

            Label:
                id: name_label2
                #text: "Here"
                font_size: 32
                size_hint: (1, 0.2)

        Button:
            text: "Submit"
            font_size: 32
            pos_hint: {'center_x': 0.5}
            size_hint: (1, 0.2)
            on_press: root.simpleiint()

        Button:
            text: 'Copy'
            font_size: 32
            pos_hint: {'center_x': 0.5}
            size_hint: (1, 0.2)
            on_release: root.copy_to_clipboard(self)

        Button:
            text: 'Show/Hide'
            font_size: 32
            pos_hint: {'center_x': 0.5}
            size_hint: (1, 0.2)
            on_press: root.toggle_password()

